 #!/bin/bash
# final-clean-fix.sh - Clean working version

echo "🔧 APPLYING CLEAN FINAL FIXES..."
echo "================================"

# Navigate to project directory
cd "$(dirname "$0")"

# Create backup
cp PureMac.swift PureMac.swift.backup-final
echo "✅ Backup created"

# First, remove all the duplicate function insertions by restoring from backup
# But we need to keep the working structure from backup

# Let's extract just the PureMacViewModel class and replace it with a clean version
awk '
BEGIN { inClass = 0; classContent = ""; }

/PureMacViewModel: ObservableObject {/ {
    inClass = 1;
    print $0;
    print ""
    print "    // MARK: - Properties"
    print "    @Published var selectedTab = 0"
    print "    @Published var isScanning = false"
    print "    @Published var scanProgress: Double = 0"
    print "    @Published var searchText = \"\""
    print "    @Published var selectedItems: Set<UUID> = []"
    print "    @Published var performanceItems: [PerformanceItem] = []"
    print "    @Published var appManagementItems: [AppItem] = []"
    print "    @Published var privacyItems: [PrivacyItem] = []"
    print "    @Published var powerUserItems: [PowerItem] = []"
    print "    @Published var mediaItems: [MediaItem] = []"
    print "    @Published var cloudItems: [CloudItem] = []"
    print "    @Published var desktopItems: [DesktopItem] = []"
    print "    @Published var reportingItems: [ReportItem] = []"
    print "    @Published var uxItems: [UXItem] = []"
    print "    @Published var smartAutomationItems: [SmartItem] = []"
    print ""
    print "    init() {"
    print "        loadPerformanceFeatures()"
    print "        loadAppManagementFeatures()"
    print "        loadPrivacyFeatures()"
    print "        loadPowerUserFeatures()"
    print "        loadMediaFeatures()"
    print "        loadCloudFeatures()"
    print "        loadDesktopFeatures()"
    print "        loadReportingFeatures()"
    print "        loadUXFeatures()"
    print "    }"
    print ""
    print "    // MARK: - Command Execution"
    print "    func executeCommand(_ command: String) {"
    print "        print(\"Executing: \\(command)\")"
    print "        let task = Process()"
    print "        task.launchPath = \"/bin/bash\""
    print "        task.arguments = [\"-c\", command]"
    print "        "
    print "        let pipe = Pipe()"
    print "        task.standardOutput = pipe"
    print "        task.standardError = pipe"
    print "        "
    print "        do {"
    print "            try task.run()"
    print "            task.waitUntilExit()"
    print "            "
    print "            let data = pipe.fileHandleForReading.readDataToEndOfFile()"
    print "            if let output = String(data: data, encoding: .utf8) {"
    print "                print(\"Output: \\(output)\")"
    print "                // Show alert with output"
    print "                DispatchQueue.main.async {"
    print "                    let alert = NSAlert()"
    print "                    alert.messageText = \"Command Executed\""
    print "                    alert.informativeText = output.isEmpty ? \"Operation completed\" : output"
    print "                    alert.runModal()"
    print "                }"
    print "            }"
    print "        } catch {"
    print "            print(\"Error: \\(error)\")"
    print "            DispatchQueue.main.async {"
    print "                let alert = NSAlert()"
    print "                alert.messageText = \"Error\""
    print "                alert.informativeText = error.localizedDescription"
    print "                alert.runModal()"
    print "            }"
    print "        }"
    print "    }"
    print ""
    print "    // MARK: - Smart Cleanup"
    print "    func smartCleanup() {"
    print "        let alert = NSAlert()"
    print "        alert.messageText = \"Smart Cleanup\""
    print "        alert.informativeText = \"This will analyze and clean temporary files, caches, and logs.\""
    print "        alert.addButton(withTitle: \"Start Cleanup\")"
    print "        alert.addButton(withTitle: \"Cancel\")"
    print "        "
    print "        if alert.runModal() == .alertFirstButtonReturn {"
    print "            executeCommand(\"echo \\\"🧹 Cleaning temporary files...\\\"; rm -rf ~/Library/Caches/* 2>/dev/null; rm -rf ~/Library/Logs/* 2>/dev/null; rm -rf ~/.Trash/* 2>/dev/null; echo \\\"✅ Cleanup complete!\\\"\")"
    print "        }"
    print "    }"
    print ""
    print "    // MARK: - Cleanup Selected Items"
    print "    func cleanupSelectedItems() {"
    print "        let alert = NSAlert()"
    print "        alert.messageText = \"Clean Selected Items\""
    print "        alert.informativeText = \"Empty Trash and clear caches?\""
    print "        alert.addButton(withTitle: \"Clean\")"
    print "        alert.addButton(withTitle: \"Cancel\")"
    print "        "
    print "        if alert.runModal() == .alertFirstButtonReturn {"
    print "            executeCommand(\"rm -rf ~/.Trash/* 2>/dev/null; rm -rf ~/Library/Caches/* 2>/dev/null; echo \\\"✅ Trash and caches cleared\\\"\")"
    print "        }"
    print "    }"
    print ""
    print "    // MARK: - Privacy Lockdown"
    print "    func privacyLockdown() {"
    print "        let alert = NSAlert()"
    print "        alert.messageText = \"Privacy Lockdown\""
    print "        alert.informativeText = \"Clear browser histories and recent documents?\""
    print "        alert.addButton(withTitle: \"Lockdown\")"
    print "        alert.addButton(withTitle: \"Cancel\")"
    print "        "
    print "        if alert.runModal() == .alertFirstButtonReturn {"
    print "            executeCommand(\"echo \\\"🔒 Clearing browser histories...\\\"; rm -f ~/Library/Safari/History.db 2>/dev/null; rm -f ~/Library/Application\\\\ Support/Google/Chrome/Default/History 2>/dev/null; rm -f ~/Library/Preferences/com.apple.recentitems.plist 2>/dev/null; echo \\\"✅ Privacy lockdown complete\\\"\")"
    print "        }"
    print "    }"
    print ""
    print "    // MARK: - Boost Performance"
    print "    func boostPerformance() {"
    print "        let alert = NSAlert()"
    print "        alert.messageText = \"Boost Performance\""
    print "        alert.informativeText = \"Clear memory cache and optimize system?\""
    print "        alert.addButton(withTitle: \"Boost\")"
    print "        alert.addButton(withTitle: \"Cancel\")"
    print "        "
    print "        if alert.runModal() == .alertFirstButtonReturn {"
    print "            executeCommand(\"echo \\\"🚀 Optimizing system...\\\"; sudo purge 2>/dev/null; echo \\\"✅ Performance boost complete\\\"\")"
    print "        }"
    print "    }"
    print ""
    print "    // MARK: - Load Features"
    print "    func loadPerformanceFeatures() {"
    print "        performanceItems = ["
    print "            PerformanceItem(name: \"Login Item Manager\", description: \"Show startup items\", icon: \"power\", color: .orange, value: \"View\", action: \"osascript -e 'tell app \\\"System Events\\\" to get name of every login item' 2>/dev/null || echo 'No login items'\"),"
    print "            PerformanceItem(name: \"Disk Health Check\", description: \"S.M.A.R.T. status\", icon: \"externaldrive\", color: .orange, value: \"Check\", action: \"diskutil info / | grep -E 'SMART|Health' || echo 'SMART status not available'\"),"
    print "            PerformanceItem(name: \"Swap Usage\", description: \"Check swap file\", icon: \"arrow.triangle.2.circlepath\", color: .orange, value: \"View\", action: \"sysctl vm.swapusage\"),"
    print "            PerformanceItem(name: \"Uptime Check\", description: \"System uptime\", icon: \"clock\", color: .orange, value: \"View\", action: \"uptime\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadAppManagementFeatures() {"
    print "        appManagementItems = ["
    print "            AppItem(name: \"Full App Uninstaller\", developer: \"System\", version: \"Interactive\", size: \"Remove apps\", icon: \"trash\", color: .red, action: \"ls -1 /Applications | head -20\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadPrivacyFeatures() {"
    print "        privacyItems = ["
    print "            PrivacyItem(name: \"Browser History Cleaner\", status: \"present\", action: \"echo 'Browser history cleaner'\", icon: \"globe\", color: .purple, details: \"Clears browser history\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadPowerUserFeatures() {"
    print "        powerUserItems = ["
    print "            PowerItem(name: \"Terminal Command Runner\", category: \"Power\", icon: \"terminal\", color: .gray, action: \"echo 'Terminal commands'\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadMediaFeatures() {"
    print "        mediaItems = ["
    print "            MediaItem(name: \"Duplicate Photo Finder\", type: \"Photos\", size: \"Scan\", icon: \"photo\", color: .pink, action: \"echo 'Duplicate finder'\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadCloudFeatures() {"
    print "        cloudItems = ["
    print "            CloudItem(name: \"iCloud Storage Check\", service: \"iCloud\", size: \"View\", icon: \"cloud\", color: .cyan, action: \"echo 'iCloud status'\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadDesktopFeatures() {"
    print "        desktopItems = ["
    print "            DesktopItem(name: \"Desktop Cleanup\", description: \"Organize desktop files\", icon: \"desktopcomputer\", color: .green, action: \"echo 'Desktop cleanup'\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadReportingFeatures() {"
    print "        reportingItems = ["
    print "            ReportItem(name: \"Disk Usage Report\", type: \"Storage\", icon: \"chart.pie\", color: .green, data: \"Current\", action: \"df -h /\")"
    print "        ]"
    print "    }"
    print "    "
    print "    func loadUXFeatures() {"
    print "        uxItems = ["
    print "            UXItem(name: \"Safe Mode\", description: \"Preview before deleting\", icon: \"shield\", color: .teal, enabled: true),"
    print "            UXItem(name: \"Dark Mode\", description: \"Dark theme UI\", icon: \"moon\", color: .teal, enabled: true)"
    print "        ]"
    print "    }"
    next;
}

!inClass { print $0 }

/PureMacViewModel: ObservableObject {/,/^}/ { if (/^}/) { inClass = 0; } next; }

END { if (inClass) print "}" }
' PureMac.swift.backup-final > PureMac-fixed.swift

mv PureMac-fixed.swift PureMac.swift
echo "✅ Replaced PureMacViewModel with clean version"

# Fix any remaining button actions
sed -i '' 's/viewModel\.executeCommand("echo .*")/viewModel.smartCleanup()/g' PureMac.swift
sed -i '' 's/Button(action: { viewModel.executeCommand("sudo .*") })/Button(action: { viewModel.privacyLockdown() })/g' PureMac.swift
sed -i '' 's/Button(action: { viewModel.executeCommand("sudo purge.*") })/Button(action: { viewModel.boostPerformance() })/g' PureMac.swift

echo ""
echo "🎉 FIXES APPLIED!"
echo "================"
echo ""

# Build
./3.sh

echo ""
echo "📝 AFTER BUILD:"
echo "1. Find PureMac.app in Finder"
echo "2. Right-click and Open (to bypass Gatekeeper)"
echo "3. Go to System Settings > Privacy & Security > Full Disk Access"
echo "4. Add PureMac.app"
echo "5. Also add to Files & Folders and Automation"
echo ""
echo "✅ All buttons should now work with proper confirmation dialogs!"